# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_auto_20180426_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='home_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='work_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
