# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_auto_20180426_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.CharField(choices=[('S0', '9:00AM-10:30AM'), ('S1', '10:30AM-12:00PM'), ('S2', '1:00PM-2:30PM'), ('S3', '2:30PM-4:00PM'), ('S4', '4:00PM-5:30PM')], default='S0', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='option',
            field=models.CharField(choices=[('WO', 'Wash Only'), ('WN', 'Wash&nail clip'), ('DG', 'Deluxe Grooming')], default='WO', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateField(),
        ),
    ]
